// Interface translations are deliberately kept separate from operational data.
// Names, product names and journal values received from Google remain unchanged.
const RU_EN = {
  "Электронные журналы производства": "Digital production journals", "Заполняйте журналы быстро, продолжайте работу без интернета и не переносите данные вручную.": "Fill in journals quickly, keep working offline and avoid manual data transfer.",
  "Google Sheets остаётся главным источником": "Google Sheets remains the primary source", "Автоматическая отправка при появлении сети": "Automatic sending when the network returns", "Автор каждой записи сохраняется": "The author of every entry is saved",
  "Выбор учётной записи": "Select an account", "Тестовый режим": "Test mode", "Кто работает?": "Who is working?", "Пароль": "Password", "Введите пароль": "Enter password", "Войти": "Sign in", "Администрация": "Administration", "Старший механик": "Senior mechanic", "Домашний компьютер администрации": "Administration home computer", "Рабочий компьютер администрации": "Administration work computer",
  "Основное меню": "Main menu", "Версия": "Version", "Обновить программу": "Update program", "Обновляем…": "Updating…", "Обновить данные и экран (как F5)": "Refresh data and screen (like F5)", "Обновить данные и экран": "Refresh data and screen",
  "Рабочий раздел": "Work section", "Раздел уже добавлен в программу. Дальше заполним его журналом, полями и статистикой по вашему рабочему порядку.": "This section is already available in the program. Its journal, fields and statistics will be completed according to your work process.",
  "Ремонт и ТО": "Repair and maintenance", "Станки": "Machines", "Обновить": "Refresh", "Журнал ремонта": "Repair log", "Журнал ТО": "Maintenance log", "Статистика": "Statistics",
  "Учёт продукции и брака": "Production and scrap accounting", "Каждый упаковщик вносит свой выпуск отдельно. Итоги линии и машины программа складывает без двойного учёта.": "Each packer records their own output. The program totals line and machine results without double counting.", "+ Внести мой выпуск": "+ Record my output", "Получаем данные из Google Sheets. Это может занять до 30 секунд.": "Loading data from Google Sheets. This can take up to 30 seconds.",
  "Готовая продукция": "Finished product", "Брак продукции": "Product scrap", "Брак банок": "Can scrap", "кг за сегодня": "kg today", "кор. за сегодня · 240 шт. в коробке": "boxes today · 240 pcs per box", "Сегодня": "Today", "Смена": "Shift", "Начало": "Start", "Окончание": "End", "Линейка продукта": "Product line", "Продукт": "Product", "Линия": "Line", "Готово, шт": "Finished, pcs", "Брак продукции, кг": "Product scrap, kg", "Брак банок, кг": "Can scrap, kg", "Упаковщик": "Packer", "Механик-оператор(ы)": "Mechanic-operator(s)", "Старший механик": "Senior mechanic", "Механик": "Mechanic", "Примечание": "Note", "Исправить": "Edit", "Удалить": "Delete", "За сегодня записей пока нет.": "No entries for today yet.",
  "Смена · персональные показатели": "Shift · personal indicators", "Кому засчитывается выпуск": "Output credited to", "Итог линии не удваивается": "Line total is not doubled", "Упаковщики": "Packers", "Механики-операторы": "Mechanic-operators", "Старший механик и Механик": "Senior mechanic and mechanic", "Сотрудник": "Employee", "Выпуск, шт": "Output, pcs", "Коробки": "Boxes", "Брак, кг": "Scrap, kg", "сменный итог": "shift total",
  "Последние записи ремонта": "Latest repair entries", "Открыть журнал": "Open log", "Таблица ТО · выпуск": "Maintenance table · output", "Остаток до ТО": "Remaining until maintenance", "5 последних": "Latest 5", "Состояние станков": "Machine status", "Рабочая": "Working", "Требует внимания": "Needs attention", "В ремонте": "Under repair", "Все станки работают": "All machines are working", "Открыть": "Open", "Обозначения": "Legend",
  "Состав текущей смены": "Current shift team", "Состав смены": "Shift team", "Учтены отмеченные в табеле сотрудники": "Employees marked in the timesheet are counted", "Состав появится после отметки табеля": "The team will appear after the timesheet is completed", "Механиков": "Mechanics",
  "Подготавливаем журналы": "Preparing journals", "Все журналы синхронизированы. Программа готова к работе.": "All journals are synchronized. The program is ready to use.", "Проверить снова": "Check again", "Повторить": "Retry", "Проверить": "Check", "Рабочая смена идёт": "Work shift is in progress", "Завершить смену": "End shift", "Смена не начата": "Shift has not started", "Перейти к табелю": "Go to timesheet",
  "Быстрый контроль весов": "Quick scale check", "Введите показание и нажмите Enter — программа сразу перейдёт к следующим весам.": "Enter a reading and press Enter — the program will move to the next scale.", "Одна запись": "One record", "Начать обход 13 весов": "Start 13-scale check", "Проверено сегодня": "Checked today", "В пределах допуска": "Within tolerance", "Вне допуска": "Out of tolerance", "Уникальных весов": "Unique scales", "Нужен комментарий": "Comment required", "Отклонений нет": "No deviations", "Период": "Period", "Отправлено": "Sent", "В очереди": "Queued", "Дата": "Date", "Весы": "Scales", "Факт": "Actual", "Отклонение": "Deviation", "Результат": "Result", "Исполнитель": "Performer", "Состояние записи": "Record status",
  "Рабочее время и смены": "Working time and shifts", "Табель участка": "Area timesheet", "График 2/2, фактические часы, причины отсутствия и начало смены — в одном разделе.": "The 2/2 schedule, actual hours, absence reasons and shift start are in one section.", "Начало смены": "Shift start", "Кто сегодня работает": "Who is working today", "График смен": "Shift schedule", "Цикл 2/2 и часы": "2/2 cycle and hours", "Табель месяца": "Monthly timesheet", "Факт и отсутствие": "Actual time and absence",
  "Расход упаковки": "Packaging consumption", "Вид упаковки": "Packaging type", "Нажмите на нужную позицию. Рядом показан уже взятый итог за день.": "Select the required item. The total already taken today is shown next to it.", "Уже взято сегодня": "Taken today", "Быстрый ввод": "Quick entry", "Выберите упаковку": "Select packaging", "Сначала выберите позицию слева.": "First select an item on the left.", "Количество": "Quantity", "Новое количество будет прибавлено к итогу за сегодня. Только целое положительное число.": "The new quantity will be added to today’s total. Only a positive whole number is allowed.", "Прибавить к итогу": "Add to total",
  "Склад упаковки": "Packaging warehouse", "Журнал несоответствий": "Nonconformity log", "Журнал инцидентов": "Incident log", "Спецификация продуктов": "Product specifications", "Учёт продукции и брака": "Production and scrap accounting", "Склад запчастей": "Spare parts warehouse", "Склад СИЗ": "PPE warehouse", "Очистка циклонов": "Cyclone cleaning", "Документы": "Documents", "Персонал": "Personnel", "График отпусков": "Vacation schedule", "Настройки": "Settings",
  "Язык и оформление": "Language and appearance", "Язык": "Language", "Тема": "Theme", "Тёмная": "Dark", "Светлая": "Light", "Дата и время": "Date and time", "Пароли учётных записей": "Account passwords", "Учётная запись": "Account", "Текущий пароль": "Current password", "Новый пароль": "New password", "Повторите новый пароль": "Repeat new password", "Сменить пароль": "Change password", "Сотрудники участка": "Area employees", "+ Добавить сотрудника": "+ Add employee", "Должность": "Position", "Статус": "Status", "Активен": "Active", "В архиве": "Archived", "Изменить": "Edit", "Вернуть": "Restore", "В архив": "Archive", "Сохранить": "Save", "Отмена": "Cancel", "Продолжить": "Continue", "Закрыть": "Close",
  "Дни рождения": "Birthdays", "Напоминания начальника": "Manager reminders", "Сегодня день рождения": "Birthday today", "Через 3 дня": "In 3 days", "Через неделю": "In a week", "Конфликт": "Conflict", "Демо": "Demo", "Аннулировано": "Cancelled", "Синхронизация": "Synchronization", "Записей пока нет": "No entries yet", "Нажмите «Новая запись», чтобы начать.": "Click “New record” to start.", "Новая запись": "New record", "Исправление": "Correction", "Аннулирование": "Cancellation",
  "Коробки с логотипом GARANT (широкая) 430×285×255": "GARANT logo boxes (wide) 430×285×255", "Коробки с логотипом Garant (узкая) 570×210×249": "Garant logo boxes (narrow) 570×210×249", "Бумага Dochems 37 GSM": "Dochems paper 37 GSM", "Банка килла прозрачная": "Killa jar, clear", "Банка килла зелёная": "Killa jar, green", "Крышка килла зелёная": "Killa lid, green", "Банка ДЗ прозрачная": "DZ jar, clear", "Банка ДЗ зелёная": "DZ jar, green", "Крышка ДЗ чёрная": "DZ lid, black", "Крышка ДЗ белая": "DZ lid, white"
};

const RU_LT = {
  "Электронные журналы производства": "Elektroniniai gamybos žurnalai", "Заполняйте журналы быстро, продолжайте работу без интернета и не переносите данные вручную.": "Pildykite žurnalus greitai, dirbkite be interneto ir neperkelkite duomenų rankiniu būdu.",
  "Google Sheets остаётся главным источником": "Google Sheets lieka pagrindiniu šaltiniu", "Автоматическая отправка при появлении сети": "Automatinis siuntimas atsiradus ryšiui", "Автор каждой записи сохраняется": "Išsaugomas kiekvieno įrašo autorius",
  "Выбор учётной записи": "Paskyros pasirinkimas", "Тестовый режим": "Bandomasis režimas", "Кто работает?": "Kas dirba?", "Пароль": "Slaptažodis", "Введите пароль": "Įveskite slaptažodį", "Войти": "Prisijungti", "Администрация": "Administracija", "Старший механик": "Vyresnysis mechanikas", "Домашний компьютер администрации": "Administracijos namų kompiuteris", "Рабочий компьютер администрации": "Administracijos darbo kompiuteris",
  "Основное меню": "Pagrindinis meniu", "Версия": "Versija", "Обновить программу": "Atnaujinti programą", "Обновляем…": "Atnaujinama…", "Обновить данные и экран (как F5)": "Atnaujinti duomenis ir ekraną (kaip F5)", "Обновить данные и экран": "Atnaujinti duomenis ir ekraną",
  "Ремонт и ТО": "Remontas ir priežiūra", "Станки": "Staklės", "Обновить": "Atnaujinti", "Журнал ремонта": "Remonto žurnalas", "Журнал ТО": "Priežiūros žurnalas", "Статистика": "Statistika",
  "Учёт продукции и брака": "Produkcijos ir broko apskaita", "Каждый упаковщик вносит свой выпуск отдельно. Итоги линии и машины программа складывает без двойного учёта.": "Kiekvienas pakuotojas registruoja savo produkciją atskirai. Programa sudeda linijos ir staklių rezultatus be dvigubo skaičiavimo.", "+ Внести мой выпуск": "+ Įrašyti mano produkciją", "Получаем данные из Google Sheets. Это может занять до 30 секунд.": "Gaunami duomenys iš Google Sheets. Tai gali užtrukti iki 30 sekundžių.",
  "Готовая продукция": "Pagaminta produkcija", "Брак продукции": "Produkcijos brokas", "Брак банок": "Indelių brokas", "кг за сегодня": "kg šiandien", "кор. за сегодня · 240 шт. в коробке": "dėž. šiandien · 240 vnt. dėžėje", "Сегодня": "Šiandien", "Смена": "Pamaina", "Начало": "Pradžia", "Окончание": "Pabaiga", "Линейка продукта": "Produkto linija", "Продукт": "Produktas", "Линия": "Linija", "Готово, шт": "Pagaminta, vnt.", "Брак продукции, кг": "Produkcijos brokas, kg", "Брак банок, кг": "Indelių brokas, kg", "Упаковщик": "Pakuotojas", "Механик-оператор(ы)": "Mechanikas-operatorius(-iai)", "Старший механик": "Vyresnysis mechanikas", "Механик": "Mechanikas", "Примечание": "Pastaba", "Исправить": "Taisyti", "Удалить": "Ištrinti", "За сегодня записей пока нет.": "Šiandien įrašų dar nėra.",
  "Смена · персональные показатели": "Pamaina · asmeniniai rodikliai", "Кому засчитывается выпуск": "Kam įskaitoma produkcija", "Итог линии не удваивается": "Linijos rezultatas nedvigubinamas", "Упаковщики": "Pakuotojai", "Механики-операторы": "Mechanikai-operatoriai", "Старший механик и Механик": "Vyresnysis mechanikas ir mechanikas", "Сотрудник": "Darbuotojas", "Выпуск, шт": "Produkcija, vnt.", "Коробки": "Dėžės", "Брак, кг": "Brokas, kg", "сменный итог": "pamainos rezultatas",
  "Последние записи ремонта": "Naujausi remonto įrašai", "Открыть журнал": "Atidaryti žurnalą", "Таблица ТО · выпуск": "Priežiūros lentelė · produkcija", "Остаток до ТО": "Liko iki priežiūros", "5 последних": "Paskutiniai 5", "Состояние станков": "Staklių būklė", "Рабочая": "Veikia", "Требует внимания": "Reikia dėmesio", "В ремонте": "Remontuojama", "Все станки работают": "Visos staklės veikia", "Открыть": "Atidaryti", "Обозначения": "Žymėjimas",
  "Состав текущей смены": "Dabartinės pamainos sudėtis", "Состав смены": "Pamainos sudėtis", "Учтены отмеченные в табеле сотрудники": "Skaičiuojami darbo laiko apskaitoje pažymėti darbuotojai", "Состав появится после отметки табеля": "Sudėtis bus parodyta užpildžius darbo laiko apskaitą", "Механиков": "Mechanikų",
  "Подготавливаем журналы": "Ruošiami žurnalai", "Все журналы синхронизированы. Программа готова к работе.": "Visi žurnalai sinchronizuoti. Programa paruošta darbui.", "Проверить снова": "Tikrinti dar kartą", "Повторить": "Bandyti dar kartą", "Проверить": "Tikrinti", "Рабочая смена идёт": "Darbo pamaina vyksta", "Завершить смену": "Baigti pamainą", "Смена не начата": "Pamaina nepradėta", "Перейти к табелю": "Eiti į darbo laiko apskaitą",
  "Быстрый контроль весов": "Greita svarstyklių patikra", "Введите показание и нажмите Enter — программа сразу перейдёт к следующим весам.": "Įveskite rodmenį ir spauskite Enter — programa pereis prie kitų svarstyklių.", "Одна запись": "Vienas įrašas", "Начать обход 13 весов": "Pradėti 13 svarstyklių patikrą", "Проверено сегодня": "Patikrinta šiandien", "В пределах допуска": "Leistinose ribose", "Вне допуска": "Už leistinų ribų", "Уникальных весов": "Unikalios svarstyklės", "Нужен комментарий": "Reikalingas komentaras", "Отклонений нет": "Nukrypimų nėra", "Период": "Laikotarpis", "Отправлено": "Išsiųsta", "В очереди": "Eilėje", "Дата": "Data", "Весы": "Svarstyklės", "Факт": "Faktas", "Отклонение": "Nukrypimas", "Результат": "Rezultatas", "Исполнитель": "Vykdytojas", "Состояние записи": "Įrašo būsena",
  "Рабочее время и смены": "Darbo laikas ir pamainos", "Табель участка": "Skyriaus darbo laiko apskaita", "Начало смены": "Pamainos pradžia", "Кто сегодня работает": "Kas šiandien dirba", "График смен": "Pamainų grafikas", "Цикл 2/2 и часы": "2/2 ciklas ir valandos", "Табель месяца": "Mėnesio apskaita", "Факт и отсутствие": "Faktas ir nebuvimas",
  "Расход упаковки": "Pakuočių sunaudojimas", "Вид упаковки": "Pakuotės tipas", "Нажмите на нужную позицию. Рядом показан уже взятый итог за день.": "Pasirinkite reikiamą poziciją. Šalia rodomas jau paimtas dienos kiekis.", "Уже взято сегодня": "Paimta šiandien", "Быстрый ввод": "Greitas įvedimas", "Выберите упаковку": "Pasirinkite pakuotę", "Сначала выберите позицию слева.": "Pirmiausia pasirinkite poziciją kairėje.", "Количество": "Kiekis", "Новое количество будет прибавлено к итогу за сегодня. Только целое положительное число.": "Naujas kiekis bus pridėtas prie šiandienos rezultato. Leidžiamas tik teigiamas sveikasis skaičius.", "Прибавить к итогу": "Pridėti prie rezultato",
  "Склад упаковки": "Pakuočių sandėlis", "Журнал несоответствий": "Neatitikčių žurnalas", "Журнал инцидентов": "Incidentų žurnalas", "Спецификация продуктов": "Produktų specifikacijos", "Склад запчастей": "Atsarginių dalių sandėlis", "Склад СИЗ": "AAP sandėlis", "Очистка циклонов": "Ciklonų valymas", "Документы": "Dokumentai", "Персонал": "Personalas", "График отпусков": "Atostogų grafikas", "Настройки": "Nustatymai",
  "Язык и оформление": "Kalba ir išvaizda", "Язык": "Kalba", "Тема": "Tema", "Тёмная": "Tamsi", "Светлая": "Šviesi", "Дата и время": "Data ir laikas", "Пароли учётных записей": "Paskyrų slaptažodžiai", "Учётная запись": "Paskyra", "Текущий пароль": "Dabartinis slaptažodis", "Новый пароль": "Naujas slaptažodis", "Повторите новый пароль": "Pakartokite naują slaptažodį", "Сменить пароль": "Keisti slaptažodį", "Сотрудники участка": "Skyriaus darbuotojai", "+ Добавить сотрудника": "+ Pridėti darbuotoją", "Должность": "Pareigos", "Статус": "Būsena", "Активен": "Aktyvus", "В архиве": "Archyve", "Изменить": "Keisti", "Вернуть": "Grąžinti", "В архив": "Į archyvą", "Сохранить": "Išsaugoti", "Отмена": "Atšaukti", "Продолжить": "Tęsti", "Закрыть": "Uždaryti",
  "Дни рождения": "Gimtadieniai", "Напоминания начальника": "Administracijos priminimai", "Сегодня день рождения": "Gimtadienis šiandien", "Через 3 дня": "Po 3 dienų", "Через неделю": "Po savaitės", "Конфликт": "Konfliktas", "Демо": "Demonstracija", "Аннулировано": "Anuliuota", "Синхронизация": "Sinchronizavimas", "Записей пока нет": "Įrašų dar nėra", "Нажмите «Новая запись», чтобы начать.": "Spustelėkite „Naujas įrašas“, kad pradėtumėte.", "Новая запись": "Naujas įrašas", "Исправление": "Taisymas", "Аннулирование": "Anuliavimas",
  "Коробки с логотипом GARANT (широкая) 430×285×255": "Dėžės su GARANT logotipu (plačios) 430×285×255", "Коробки с логотипом Garant (узкая) 570×210×249": "Dėžės su Garant logotipu (siauros) 570×210×249", "Бумага Dochems 37 GSM": "Dochems popierius 37 GSM", "Банка килла прозрачная": "Skaidrus Killa indelis", "Банка килла зелёная": "Žalias Killa indelis", "Крышка килла зелёная": "Žalias Killa dangtelis", "Банка ДЗ прозрачная": "Skaidrus DZ indelis", "Банка ДЗ зелёная": "Žalias DZ indelis", "Крышка ДЗ чёрная": "Juodas DZ dangtelis", "Крышка ДЗ белая": "Baltas DZ dangtelis"
};

// Remaining page, table, dialog and status strings.  Keeping these in the same
// catalog lets every view use one rendering path instead of maintaining three
// copies of a journal form.
Object.assign(RU_EN, {
  "Проверено:": "Checked:", "шт.": "pcs", "кор.": "boxes", "рул.": "rolls", "записей": "entries", "записи": "entries", "запись": "entry",
  "Смена B работает по графику": "Shift B is scheduled to work", "Цикл 2 рабочих / 2 выходных · 12 ч на производстве · 11 учётных часов": "2 workdays / 2 days off · 12 h in production · 11 recorded hours",
  "ШАГ 1 · СОСТАВ СМЕНЫ": "STEP 1 · SHIFT TEAM", "Исправить присутствие": "Edit attendance", "Выберите смену, отметьте присутствующих, затем назначьте старшего механика и механика.": "Select a shift, mark attendees, then assign the senior mechanic and mechanic.", "Рабочая смена": "Work shift", "Выберите сотрудника": "Select employee", "На работе": "At work", "полная": "full", "на работе": "at work", "Сохранить исправления": "Save changes", "Добавить сотрудника другой смены": "Add employee from another shift",
  "Последнее чтение Google:": "Last Google read:", "В очереди:": "Queued:", "Исправить итог за сегодня": "Edit today’s total", "Обновить каталог": "Refresh catalog", "Открыть в Google Sheets ↗": "Open in Google Sheets ↗", "+ Новое движение": "+ New movement",
  "Google Sheets · упаковочные материалы": "Google Sheets · packaging materials", "Приход и расход сохраняются в общем журнале. Расчётный остаток считается автоматически, фактический заполняется при инвентаризации.": "Receipts and issues are saved in a shared journal. The calculated balance is automatic; the actual balance is entered during stocktaking.", "Остатки: расчёт и факт": "Balances: calculated and actual", "Общий склад": "Shared warehouse", "НАИМЕНОВАНИЕ": "ITEM", "ЕД.": "UNIT", "НАЧАЛЬНЫЙ": "OPENING", "ПРИХОД": "RECEIPT", "РАСХОД": "ISSUE", "РАСЧЁТНЫЙ": "CALCULATED", "ФАКТИЧЕСКИЙ": "ACTUAL", "РАЗНИЦА": "DIFFERENCE", "КОММЕНТАРИЙ": "COMMENT", "Приход": "Receipt", "Расход": "Issue", "Наименование": "Item", "Операция": "Operation", "Внёс": "Recorded by", "Журнал движений": "Movement log", "Движений склада пока нет. Внесите первый приход или расход.": "No warehouse movements yet. Record the first receipt or issue.",
  "Клик: рабочая → требует внимания → в ремонте": "Click: working → needs attention → under repair", "Только просмотр": "View only", "Добавить ремонт": "Add repair", "РЕМОНТ": "REPAIR", "Дата": "Date", "Станок": "Machine", "Категория": "Category", "Вид работ": "Work type", "ИСПОЛНИТЕЛЬ": "PERFORMER", "ПРИМЕЧАНИЕ": "NOTE", "КАТЕГОРИЯ": "CATEGORY", "ВИД РАБОТ": "WORK TYPE", "Станок 8": "Machine 8", "Станок 14": "Machine 14", "Станок 6": "Machine 6",
  "Google Sheets · журнал и сводка": "Google Sheets · log and summary", "Несоответствия": "Nonconformities", "Показан текущий месяц. Дата и смена берутся из табеля; виды несоответствий — из рабочего справочника.": "The current month is shown. Date and shift come from the timesheet; nonconformity types come from the working catalog.", "+ Новое несоответствие": "+ New nonconformity", "За текущий месяц": "This month", "Требуют завершения": "Need completion", "Категории": "Categories", "статус не «Выполнено»": "status is not “Completed”", "за текущий месяц": "this month", "ТЕКУЩИЙ ПЕРИОД": "CURRENT PERIOD", "Вид": "Type", "Причина": "Cause", "Корректирующие действия": "Corrective actions", "Ответственный": "Responsible", "Дата и смена привязаны к табелю.": "Date and shift are linked to the timesheet.", "Для подробностей используйте «Исправить».": "Use “Edit” for details.", "Выполнено": "Completed",
  "ЛОКАЛЬНЫЙ ЖУРНАЛ · БЕЗОПАСНОСТЬ И РАБОТА УЧАСТКА": "LOCAL LOG · SAFETY AND AREA OPERATIONS", "Журнал регистрации инцидентов": "Incident register", "Фиксируйте событие сразу: что произошло, какие меры приняты и кому требуется завершить действие.": "Record the event immediately: what happened, which measures were taken and who must complete the action.", "+ Зарегистрировать инцидент": "+ Register incident", "Всего записей": "Total entries", "в этом компьютере": "on this computer", "статус не «Закрыт»": "status is not “Closed”", "Все инциденты": "All incidents", "Дата и время": "Date and time", "Описание события": "Event description", "Принятые меры": "Actions taken", "Сообщил": "Reported by", "Инцидентов пока не зарегистрировано.": "No incidents registered yet.", "Открыт": "Open", "В работе": "In progress", "Закрыт": "Closed",
  "Google Sheets · утверждённые нормы": "Google Sheets · approved standards", "Добавляйте и исправляйте продукты прямо в программе. Каталог обновляется из Google Sheets без ручного переноса.": "Add and edit products directly in the program. The catalog is refreshed from Google Sheets without manual transfer.", "+ Добавить продукт": "+ Add product", "Источник Google ↗": "Google source ↗", "Поиск по каталогу": "Catalog search", "Название продукта, линейка, mg/g, банка или крышка": "Product name, line, mg/g, jar or lid", "Все линейки": "All lines", "Все продукты": "All products", "Все варианты": "All variants", "КАТАЛОГ": "CATALOG", "Быстрый выбор": "Quick selection", "Сначала — позиции, которые чаще всего встречаются в журнале продукции.": "First — items most often used in the production log.", "показано": "shown", "Выберите позицию": "Select an item", "Найдите продукт или выберите его из каталога — здесь сразу появятся технологические нормы и упаковка.": "Find a product or select it from the catalog — process standards and packaging will appear here.",
  "Последнее чтение Google": "Last Google read", "Записать очистку": "Record cleaning", "Обновить и отправить очередь": "Refresh and send queue", "Год": "Year", "Подтверждено Google:": "Confirmed by Google:", "Очистки по месяцам": "Cleanings by month", "МЕСЯЦ": "MONTH", "ОЧИСТОК": "CLEANINGS", "Статистика рассчитана по последним прочитанным данным Google. Записи в очереди не включены.": "Statistics are based on the latest data read from Google. Queued entries are not included.", "Статистика": "Statistics",
  "КОМАНДА ФАСОВОЧНОГО УЧАСТКА": "PACKAGING AREA TEAM", "Полный справочник: состав смен, статус и личные данные сотрудников.": "Complete directory: shift teams, status and employee details.", "сотрудников": "employees", "Поиск": "Search", "Имя или фамилия…": "First or last name…", "Все смены": "All shifts", "Все должности": "All positions", "График": "Schedule", "Личные сведения": "Personal details", "Карточка": "Card", "Archive": "Archive", "Смена": "Shift",
  "ЦЕНТР УПРАВЛЕНИЯ": "CONTROL CENTRE", "Настройки участка": "Area settings", "Здесь действительно настраиваются сотрудники, смены и правила табеля. Изменения сохраняются локально и будут подключены к рабочему источнику.": "Employees, shifts and timesheet rules are configured here. Changes are saved locally and will be connected to the working source.", "Только начальник": "Manager only", "Общие": "General", "Смены": "Shifts", "Табель": "Timesheet", "ИНТЕГРАЦИЯ": "INTEGRATION", "Рабочий шлюз": "Working gateway", "Рабочая таблица": "Working sheet", "Подключение подготовлено": "Connection prepared", "Автообновление": "Automatic updates", "Доступная проверенная версия устанавливается автоматически": "An available verified version is installed automatically", "Каждую минуту": "Every minute", "Запись в Google": "Google writing", "Включена": "Enabled", "Через защищённый шлюз": "Through a secure gateway", "Часовой пояс": "Time zone", "Дата и время заполняются автоматически": "Date and time are filled automatically", "ПРОГРАММА": "PROGRAM", "Актуально": "Up to date", "Обновление": "Update", "Установлено": "Installed", "Новая версия не найдена": "No new version found", "Проверить сейчас": "Check now", "ИНТЕРФЕЙС": "INTERFACE", "ДОСТУП К ПРОГРАММЕ": "PROGRAM ACCESS", "Только этот компьютер": "This computer only"
});

Object.assign(RU_LT, {
  "Проверено:": "Patikrinta:", "шт.": "vnt.", "кор.": "dėž.", "рул.": "rit.", "записей": "įrašų", "записи": "įrašai", "запись": "įrašas",
  "Смена B работает по графику": "B pamaina dirba pagal grafiką", "Цикл 2 рабочих / 2 выходных · 12 ч на производстве · 11 учётных часов": "2 darbo dienos / 2 poilsio dienos · 12 val. gamyboje · 11 apskaitos val.",
  "ШАГ 1 · СОСТАВ СМЕНЫ": "1 ŽINGSNIS · PAMAINOS SUDĖTIS", "Исправить присутствие": "Keisti dalyvavimą", "Выберите смену, отметьте присутствующих, затем назначьте старшего механика и механика.": "Pasirinkite pamainą, pažymėkite dalyvaujančius, tada paskirkite vyresnįjį mechaniką ir mechaniką.", "Рабочая смена": "Darbo pamaina", "Выберите сотрудника": "Pasirinkite darbuotoją", "На работе": "Darbe", "полная": "visa", "на работе": "darbe", "Сохранить исправления": "Išsaugoti pakeitimus", "Добавить сотрудника другой смены": "Pridėti darbuotoją iš kitos pamainos",
  "Последнее чтение Google:": "Paskutinis Google nuskaitymas:", "В очереди:": "Eilėje:", "Исправить итог за сегодня": "Taisyti šiandienos rezultatą", "Обновить каталог": "Atnaujinti katalogą", "Открыть в Google Sheets ↗": "Atidaryti Google Sheets ↗", "+ Новое движение": "+ Naujas judėjimas",
  "Google Sheets · упаковочные материалы": "Google Sheets · pakavimo medžiagos", "Приход и расход сохраняются в общем журнале. Расчётный остаток считается автоматически, фактический заполняется при инвентаризации.": "Gavimai ir nurašymai saugomi bendrame žurnale. Apskaičiuotas likutis skaičiuojamas automatiškai, faktinis įvedamas inventorizacijos metu.", "Остатки: расчёт и факт": "Likučiai: apskaičiuoti ir faktiniai", "Общий склад": "Bendras sandėlis", "НАИМЕНОВАНИЕ": "PAVADINIMAS", "ЕД.": "VNT.", "НАЧАЛЬНЫЙ": "PRADINIS", "ПРИХОД": "GAVIMAS", "РАСХОД": "NURAŠYMAS", "РАСЧЁТНЫЙ": "APSKAIČIUOTAS", "ФАКТИЧЕСКИЙ": "FAKTINIS", "РАЗНИЦА": "SKIRTUMAS", "КОММЕНТАРИЙ": "KOMENTARAS", "Приход": "Gavimas", "Расход": "Nurašymas", "Наименование": "Pavadinimas", "Операция": "Operacija", "Внёс": "Įvedė", "Журнал движений": "Judėjimo žurnalas", "Движений склада пока нет. Внесите первый приход или расход.": "Sandėlio judėjimų dar nėra. Įveskite pirmą gavimą arba nurašymą.",
  "Клик: рабочая → требует внимания → в ремонте": "Spustelėkite: veikia → reikia dėmesio → remontuojama", "Только просмотр": "Tik peržiūra", "Добавить ремонт": "Pridėti remontą", "РЕМОНТ": "REMONTAS", "Дата": "Data", "Станок": "Staklės", "Категория": "Kategorija", "Вид работ": "Darbų tipas", "ИСПОЛНИТЕЛЬ": "VYKDYTOJAS", "ПРИМЕЧАНИЕ": "PASTABA", "КАТЕГОРИЯ": "KATEGORIJA", "ВИД РАБОТ": "DARBŲ TIPAS", "Станок 8": "Staklės 8", "Станок 14": "Staklės 14", "Станок 6": "Staklės 6",
  "Google Sheets · журнал и сводка": "Google Sheets · žurnalas ir suvestinė", "Несоответствия": "Neatitiktys", "Показан текущий месяц. Дата и смена берутся из табеля; виды несоответствий — из рабочего справочника.": "Rodomas dabartinis mėnuo. Data ir pamaina imamos iš darbo laiko apskaitos; neatitikčių tipai — iš darbo katalogo.", "+ Новое несоответствие": "+ Nauja neatitiktis", "За текущий месяц": "Šį mėnesį", "Требуют завершения": "Reikia užbaigti", "Категории": "Kategorijos", "статус не «Выполнено»": "būsena ne „Atlikta“", "за текущий месяц": "šį mėnesį", "ТЕКУЩИЙ ПЕРИОД": "DABARTINIS LAIKOTARPIS", "Вид": "Tipas", "Причина": "Priežastis", "Корректирующие действия": "Korekciniai veiksmai", "Ответственный": "Atsakingas", "Дата и смена привязаны к табелю.": "Data ir pamaina susietos su darbo laiko apskaita.", "Для подробностей используйте «Исправить».": "Išsamiai informacijai naudokite „Taisyti“.", "Выполнено": "Atlikta",
  "ЛОКАЛЬНЫЙ ЖУРНАЛ · БЕЗОПАСНОСТЬ И РАБОТА УЧАСТКА": "VIETINIS ŽURNALAS · SAUGA IR SKYRIAUS DARBAS", "Журнал регистрации инцидентов": "Incidentų registras", "Фиксируйте событие сразу: что произошло, какие меры приняты и кому требуется завершить действие.": "Registruokite įvykį iškart: kas nutiko, kokių priemonių imtasi ir kas turi užbaigti veiksmą.", "+ Зарегистрировать инцидент": "+ Registruoti incidentą", "Всего записей": "Iš viso įrašų", "в этом компьютере": "šiame kompiuteryje", "статус не «Закрыт»": "būsena ne „Uždaryta“", "Все инциденты": "Visi incidentai", "Дата и время": "Data ir laikas", "Описание события": "Įvykio aprašymas", "Принятые меры": "Priimtos priemonės", "Сообщил": "Pranešė", "Инцидентов пока не зарегистрировано.": "Incidentų dar neužregistruota.", "Открыт": "Atidarytas", "В работе": "Vykdomas", "Закрыт": "Uždarytas",
  "Google Sheets · утверждённые нормы": "Google Sheets · patvirtintos normos", "Добавляйте и исправляйте продукты прямо в программе. Каталог обновляется из Google Sheets без ручного переноса.": "Pridėkite ir keiskite produktus tiesiog programoje. Katalogas atnaujinamas iš Google Sheets be rankinio perkėlimo.", "+ Добавить продукт": "+ Pridėti produktą", "Источник Google ↗": "Google šaltinis ↗", "Поиск по каталогу": "Paieška kataloge", "Название продукта, линейка, mg/g, банка или крышка": "Produkto pavadinimas, linija, mg/g, indelis arba dangtelis", "Все линейки": "Visos linijos", "Все продукты": "Visi produktai", "Все варианты": "Visi variantai", "КАТАЛОГ": "KATALOGAS", "Быстрый выбор": "Greitas pasirinkimas", "Сначала — позиции, которые чаще всего встречаются в журнале продукции.": "Pirmiausia — pozicijos, dažniausiai pasitaikančios produkcijos žurnale.", "показано": "rodoma", "Выберите позицию": "Pasirinkite poziciją", "Найдите продукт или выберите его из каталога — здесь сразу появятся технологические нормы и упаковка.": "Raskite produktą arba pasirinkite jį iš katalogo — čia iškart bus rodomos technologinės normos ir pakuotė.",
  "Последнее чтение Google": "Paskutinis Google nuskaitymas", "Записать очистку": "Įrašyti valymą", "Обновить и отправить очередь": "Atnaujinti ir siųsti eilę", "Год": "Metai", "Подтверждено Google:": "Patvirtinta Google:", "Очистки по месяцам": "Valymai pagal mėnesius", "МЕСЯЦ": "MĖNUO", "ОЧИСТОК": "VALYMŲ", "Статистика рассчитана по последним прочитанным данным Google. Записи в очереди не включены.": "Statistika apskaičiuota pagal paskutinius iš Google nuskaitytus duomenis. Eilėje esantys įrašai neįtraukti.", "Статистика": "Statistika",
  "КОМАНДА ФАСОВОЧНОГО УЧАСТКА": "FASAVIMO SKYRIAUS KOMANDA", "Полный справочник: состав смен, статус и личные данные сотрудников.": "Pilnas katalogas: pamainų sudėtis, būsena ir darbuotojų asmeniniai duomenys.", "сотрудников": "darbuotojų", "Поиск": "Paieška", "Имя или фамилия…": "Vardas arba pavardė…", "Все смены": "Visos pamainos", "Все должности": "Visos pareigos", "График": "Grafikas", "Личные сведения": "Asmeniniai duomenys", "Карточка": "Kortelė", "Archive": "Archyvas", "Смена": "Pamaina",
  "ЦЕНТР УПРАВЛЕНИЯ": "VALDYMO CENTRAS", "Настройки участка": "Skyriaus nustatymai", "Здесь действительно настраиваются сотрудники, смены и правила табеля. Изменения сохраняются локально и будут подключены к рабочему источнику.": "Čia nustatomi darbuotojai, pamainos ir darbo laiko apskaitos taisyklės. Pakeitimai saugomi vietoje ir bus prijungti prie darbo šaltinio.", "Только начальник": "Tik administracija", "Общие": "Bendri", "Смены": "Pamainos", "Табель": "Darbo laiko apskaita", "ИНТЕГРАЦИЯ": "INTEGRACIJA", "Рабочий шлюз": "Darbinis šliuzas", "Рабочая таблица": "Darbinė lentelė", "Подключение подготовлено": "Ryšys paruoštas", "Автообновление": "Automatinis atnaujinimas", "Доступная проверенная версия устанавливается автоматически": "Prieinama patikrinta versija įdiegiama automatiškai", "Каждую минуту": "Kas minutę", "Запись в Google": "Rašymas į Google", "Включена": "Įjungta", "Через защищённый шлюз": "Per saugų šliuzą", "Часовой пояс": "Laiko juosta", "Дата и время заполняются автоматически": "Data ir laikas užpildomi automatiškai", "ПРОГРАММА": "PROGRAMA", "Актуально": "Atnaujinta", "Обновление": "Atnaujinimas", "Установлено": "Įdiegta", "Новая версия не найдена": "Naujos versijos nerasta", "Проверить сейчас": "Tikrinti dabar", "ИНТЕРФЕЙС": "SĄSAJA", "ДОСТУП К ПРОГРАММЕ": "PRIEIGA PRIE PROGRAMOS", "Только этот компьютер": "Tik šis kompiuteris"
});

const DICTIONARIES = Object.freeze({ en: RU_EN, lt: RU_LT });

function preserveWhitespace(value, translated) {
  const before = value.match(/^\s*/)?.[0] ?? "";
  const after = value.match(/\s*$/)?.[0] ?? "";
  return `${before}${translated}${after}`;
}

export function translateUiText(value, language) {
  if (language === "ru" || typeof value !== "string") return value;
  const dictionary = DICTIONARIES[language] ?? {};
  const key = value.trim();
  const translated = dictionary[key];
  if (translated) return preserveWhitespace(value, translated);
  const patterns = language === "en"
    ? [[/^Сегодня · /, "Today · "], [/^Версия /, "Version "], [/^Проверено:\s*/, "Checked: "], [/^Последнее чтение Google:\s*/, "Last Google read: "], [/^В очереди:\s*/, "Queued: "], [/^В ремонте: /, "Under repair: "], [/^Требуют внимания: /, "Need attention: "], [/^(\d+) из (\d+) на работе$/, "$1 of $2 at work"], [/^(\d+) сотрудников$/, "$1 employees"], [/^(\d+) записей$/, "$1 entries"], [/^(\d+) показано$/, "$1 shown"], [/^Требуется ТО:/, "Maintenance required:"], [/\bшт\.$/, "pcs"], [/\bкор\.$/, "boxes"], [/\bрул\.$/, "rolls"]]
    : [[/^Сегодня · /, "Šiandien · "], [/^Версия /, "Versija "], [/^Проверено:\s*/, "Patikrinta: "], [/^Последнее чтение Google:\s*/, "Paskutinis Google nuskaitymas: "], [/^В очереди:\s*/, "Eilėje: "], [/^В ремонте: /, "Remontuojama: "], [/^Требуют внимания: /, "Reikia dėmesio: "], [/^(\d+) из (\d+) на работе$/, "$1 iš $2 darbe"], [/^(\d+) сотрудников$/, "$1 darbuotojų"], [/^(\d+) записей$/, "$1 įrašų"], [/^(\d+) показано$/, "$1 rodoma"], [/^Требуется ТО:/, "Reikalinga priežiūra:"], [/\bшт\.$/, "vnt."], [/\bкор\.$/, "dėž."], [/\bрул\.$/, "rit."]];
  for (const [expression, replacement] of patterns) {
    if (expression.test(key)) return preserveWhitespace(value, key.replace(expression, replacement));
  }
  return value;
}

export function localizeElement(element, language) {
  if (!element || language === "ru") return;
  const walker = document.createTreeWalker(element, NodeFilter.SHOW_TEXT);
  const nodes = [];
  while (walker.nextNode()) nodes.push(walker.currentNode);
  nodes.forEach(node => { node.nodeValue = translateUiText(node.nodeValue, language); });
  element.querySelectorAll("[placeholder],[title],[aria-label]").forEach(node => {
    ["placeholder", "title", "aria-label"].forEach(attribute => {
      if (node.hasAttribute(attribute)) node.setAttribute(attribute, translateUiText(node.getAttribute(attribute), language));
    });
  });
}
