// Interface translations are deliberately kept separate from operational data.
// Names, product names and journal values received from Google remain unchanged.
const RU_EN = {
  "Электронные журналы производства": "Digital production journals", "Заполняйте журналы быстро, продолжайте работу без интернета и не переносите данные вручную.": "Fill in journals quickly, keep working offline and avoid manual data transfer.",
  "Google Sheets остаётся главным источником": "Google Sheets remains the primary source", "Автоматическая отправка при появлении сети": "Automatic sending when the network returns", "Автор каждой записи сохраняется": "The author of every entry is saved",
  "Выбор учётной записи": "Select an account", "Тестовый режим": "Test mode", "Кто работает?": "Who is working?", "Пароль": "Password", "Введите пароль": "Enter password", "Войти": "Sign in", "Администрация": "Administration", "Старший механик": "Senior mechanic", "Домашний компьютер администрации": "Administration home computer", "Рабочий компьютер администрации": "Administration work computer",
  "Основное меню": "Main menu", "Версия": "Version", "Обновить программу": "Update program", "Обновляем…": "Updating…", "Обновить данные и экран (как F5)": "Refresh data and screen (like F5)", "Обновить данные и экран": "Refresh data and screen",
  "Рабочий раздел": "Work section", "Раздел уже добавлен в программу. Дальше заполним его журналом, полями и статистикой по вашему рабочему порядку.": "This section is already available in the program. Its journal, fields and statistics will be completed according to your work process.",
  "Ремонт и ТО": "Repair and maintenance", "Станки": "Machines", "Обновить": "Refresh", "Журнал ремонта": "Repair log", "Журнал ТО": "Maintenance log", "Статистика": "Statistics",
  "Учёт продукции и брака": "Production and scrap accounting", "Каждый упаковщик вносит свой выпуск отдельно. Итоги линии и машины программа складывает без двойного учёта.": "Each packer records their own output. The program totals line and machine results without double counting.", "+ Внести мой выпуск": "+ Record my output", "Получаем данные из Google Sheets. Это может занять до 30 секунд.": "Loading data from Google Sheets. This can take up to 30 seconds.",
  "Готовая продукция": "Finished product", "Брак продукции": "Product scrap", "Брак банок": "Can scrap", "кг за сегодня": "kg today", "кор. за сегодня · 240 шт. в коробке": "boxes today · 240 pcs per box", "Сегодня": "Today", "Смена": "Shift", "Начало": "Start", "Окончание": "End", "Линейка продукта": "Product line", "Продукт": "Product", "Линия": "Line", "Готово, шт": "Finished, pcs", "Брак продукции, кг": "Product scrap, kg", "Брак банок, кг": "Can scrap, kg", "Упаковщик": "Packer", "Механик-оператор(ы)": "Mechanic-operator(s)", "Старший механик": "Senior mechanic", "Механик": "Mechanic", "Примечание": "Note", "Исправить": "Edit", "Удалить": "Delete", "За сегодня записей пока нет.": "No entries for today yet.",
  "Смена · персональные показатели": "Shift · personal indicators", "Кому засчитывается выпуск": "Output credited to", "Итог линии не удваивается": "Line total is not doubled", "Упаковщики": "Packers", "Механики-операторы": "Mechanic-operators", "Старший механик и Механик": "Senior mechanic and mechanic", "Сотрудник": "Employee", "Выпуск, шт": "Output, pcs", "Коробки": "Boxes", "Брак, кг": "Scrap, kg", "сменный итог": "shift total",
  "Последние записи ремонта": "Latest repair entries", "Открыть журнал": "Open log", "Таблица ТО · выпуск": "Maintenance table · output", "Остаток до ТО": "Remaining until maintenance", "5 последних": "Latest 5", "Состояние станков": "Machine status", "Рабочая": "Working", "Требует внимания": "Needs attention", "В ремонте": "Under repair", "Все станки работают": "All machines are working", "Открыть": "Open", "Обозначения": "Legend",
  "Состав текущей смены": "Current shift team", "Состав смены": "Shift team", "Учтены отмеченные в табеле сотрудники": "Employees marked in the timesheet are counted", "Состав появится после отметки табеля": "The team will appear after the timesheet is completed", "Механиков": "Mechanics",
  "Подготавливаем журналы": "Preparing journals", "Все журналы синхронизированы. Программа готова к работе.": "All journals are synchronized. The program is ready to use.", "Проверить снова": "Check again", "Повторить": "Retry", "Проверить": "Check", "Рабочая смена идёт": "Work shift is in progress", "Завершить смену": "End shift", "Смена не начата": "Shift has not started", "Перейти к табелю": "Go to timesheet",
  "Быстрый контроль весов": "Quick scale check", "Введите показание и нажмите Enter — программа сразу перейдёт к следующим весам.": "Enter a reading and press Enter — the program will move to the next scale.", "Одна запись": "One record", "Начать обход 13 весов": "Start 13-scale check", "Проверено сегодня": "Checked today", "В пределах допуска": "Within tolerance", "Вне допуска": "Out of tolerance", "Уникальных весов": "Unique scales", "Нужен комментарий": "Comment required", "Отклонений нет": "No deviations", "Период": "Period", "Отправлено": "Sent", "В очереди": "Queued", "Дата": "Date", "Весы": "Scales", "Факт": "Actual", "Отклонение": "Deviation", "Результат": "Result", "Исполнитель": "Performer", "Состояние записи": "Record status",
  "Рабочее время и смены": "Working time and shifts", "Табель участка": "Area timesheet", "График 2/2, фактические часы, причины отсутствия и начало смены — в одном разделе.": "The 2/2 schedule, actual hours, absence reasons and shift start are in one section.", "Начало смены": "Shift start", "Кто сегодня работает": "Who is working today", "График смен": "Shift schedule", "Цикл 2/2 и часы": "2/2 cycle and hours", "Табель месяца": "Monthly timesheet", "Факт и отсутствие": "Actual time and absence",
  "Расход упаковки": "Packaging consumption", "Вид упаковки": "Packaging type", "Нажмите на нужную позицию. Рядом показан уже взятый итог за день.": "Select the required item. The total already taken today is shown next to it.", "Уже взято сегодня": "Taken today", "Быстрый ввод": "Quick entry", "Выберите упаковку": "Select packaging", "Сначала выберите позицию слева.": "First select an item on the left.", "Количество": "Quantity", "Новое количество будет прибавлено к итогу за сегодня. Только целое положительное число.": "The new quantity will be added to today’s total. Only a positive whole number is allowed.", "Прибавить к итогу": "Add to total",
  "Склад упаковки": "Packaging warehouse", "Журнал несоответствий": "Nonconformity log", "Журнал инцидентов": "Incident log", "Спецификация продуктов": "Product specifications", "Учёт продукции и брака": "Production and scrap accounting", "Склад запчастей": "Spare parts warehouse", "Склад СИЗ": "PPE warehouse", "Очистка циклонов": "Cyclone cleaning", "Документы": "Documents", "Персонал": "Personnel", "График отпусков": "Vacation schedule", "Настройки": "Settings",
  "Язык и оформление": "Language and appearance", "Язык": "Language", "Тема": "Theme", "Тёмная": "Dark", "Светлая": "Light", "Дата и время": "Date and time", "Пароли учётных записей": "Account passwords", "Учётная запись": "Account", "Текущий пароль": "Current password", "Новый пароль": "New password", "Повторите новый пароль": "Repeat new password", "Сменить пароль": "Change password", "Сотрудники участка": "Area employees", "+ Добавить сотрудника": "+ Add employee", "Должность": "Position", "Статус": "Status", "Активен": "Active", "В архиве": "Archived", "Изменить": "Edit", "Вернуть": "Restore", "В архив": "Archive", "Сохранить": "Save", "Отмена": "Cancel", "Продолжить": "Continue", "Закрыть": "Close",
  "Дни рождения": "Birthdays", "Напоминания начальника": "Manager reminders", "Сегодня день рождения": "Birthday today", "Через 3 дня": "In 3 days", "Через неделю": "In a week", "Конфликт": "Conflict", "Демо": "Demo", "Аннулировано": "Cancelled", "Синхронизация": "Synchronization", "Записей пока нет": "No entries yet", "Нажмите «Новая запись», чтобы начать.": "Click “New record” to start.", "Новая запись": "New record", "Исправление": "Correction", "Аннулирование": "Cancellation",
  "Коробки с логотипом GARANT (широкая) 430×285×255": "GARANT logo boxes (wide) 430×285×255", "Коробки с логотипом Garant (узкая) 570×210×249": "Garant logo boxes (narrow) 570×210×249", "Бумага Dochems 37 GSM": "Dochems paper 37 GSM", "Банка килла прозрачная": "Killa jar, clear", "Банка килла зелёная": "Killa jar, green", "Крышка килла зелёная": "Killa lid, green", "Банка ДЗ прозрачная": "DZ jar, clear", "Банка ДЗ зелёная": "DZ jar, green", "Крышка ДЗ чёрная": "DZ lid, black", "Крышка ДЗ белая": "DZ lid, white"
};

const RU_LT = {
  "Электронные журналы производства": "Elektroniniai gamybos žurnalai", "Заполняйте журналы быстро, продолжайте работу без интернета и не переносите данные вручную.": "Pildykite žurnalus greitai, dirbkite be interneto ir neperkelkite duomenų rankiniu būdu.",
  "Google Sheets остаётся главным источником": "Google Sheets lieka pagrindiniu šaltiniu", "Автоматическая отправка при появлении сети": "Automatinis siuntimas atsiradus ryšiui", "Автор каждой записи сохраняется": "Išsaugomas kiekvieno įrašo autorius",
  "Выбор учётной записи": "Paskyros pasirinkimas", "Тестовый режим": "Bandomasis režimas", "Кто работает?": "Kas dirba?", "Пароль": "Slaptažodis", "Введите пароль": "Įveskite slaptažodį", "Войти": "Prisijungti", "Администрация": "Administracija", "Старший механик": "Vyresnysis mechanikas", "Домашний компьютер администрации": "Administracijos namų kompiuteris", "Рабочий компьютер администрации": "Administracijos darbo kompiuteris",
  "Основное меню": "Pagrindinis meniu", "Версия": "Versija", "Обновить программу": "Atnaujinti programą", "Обновляем…": "Atnaujinama…", "Обновить данные и экран (как F5)": "Atnaujinti duomenis ir ekraną (kaip F5)", "Обновить данные и экран": "Atnaujinti duomenis ir ekraną",
  "Ремонт и ТО": "Remontas ir priežiūra", "Станки": "Staklės", "Обновить": "Atnaujinti", "Журнал ремонта": "Remonto žurnalas", "Журнал ТО": "Priežiūros žurnalas", "Статистика": "Statistika",
  "Учёт продукции и брака": "Produkcijos ir broko apskaita", "Каждый упаковщик вносит свой выпуск отдельно. Итоги линии и машины программа складывает без двойного учёта.": "Kiekvienas pakuotojas registruoja savo produkciją atskirai. Programa sudeda linijos ir staklių rezultatus be dvigubo skaičiavimo.", "+ Внести мой выпуск": "+ Įrašyti mano produkciją", "Получаем данные из Google Sheets. Это может занять до 30 секунд.": "Gaunami duomenys iš Google Sheets. Tai gali užtrukti iki 30 sekundžių.",
  "Готовая продукция": "Pagaminta produkcija", "Брак продукции": "Produkcijos brokas", "Брак банок": "Indelių brokas", "кг за сегодня": "kg šiandien", "кор. за сегодня · 240 шт. в коробке": "dėž. šiandien · 240 vnt. dėžėje", "Сегодня": "Šiandien", "Смена": "Pamaina", "Начало": "Pradžia", "Окончание": "Pabaiga", "Линейка продукта": "Produkto linija", "Продукт": "Produktas", "Линия": "Linija", "Готово, шт": "Pagaminta, vnt.", "Брак продукции, кг": "Produkcijos brokas, kg", "Брак банок, кг": "Indelių brokas, kg", "Упаковщик": "Pakuotojas", "Механик-оператор(ы)": "Mechanikas-operatorius(-iai)", "Старший механик": "Vyresnysis mechanikas", "Механик": "Mechanikas", "Примечание": "Pastaba", "Исправить": "Taisyti", "Удалить": "Ištrinti", "За сегодня записей пока нет.": "Šiandien įrašų dar nėra.",
  "Смена · персональные показатели": "Pamaina · asmeniniai rodikliai", "Кому засчитывается выпуск": "Kam įskaitoma produkcija", "Итог линии не удваивается": "Linijos rezultatas nedvigubinamas", "Упаковщики": "Pakuotojai", "Механики-операторы": "Mechanikai-operatoriai", "Старший механик и Механик": "Vyresnysis mechanikas ir mechanikas", "Сотрудник": "Darbuotojas", "Выпуск, шт": "Produkcija, vnt.", "Коробки": "Dėžės", "Брак, кг": "Brokas, kg", "сменный итог": "pamainos rezultatas",
  "Последние записи ремонта": "Naujausi remonto įrašai", "Открыть журнал": "Atidaryti žurnalą", "Таблица ТО · выпуск": "Priežiūros lentelė · produkcija", "Остаток до ТО": "Liko iki priežiūros", "5 последних": "Paskutiniai 5", "Состояние станков": "Staklių būklė", "Рабочая": "Veikia", "Требует внимания": "Reikia dėmesio", "В ремонте": "Remontuojama", "Все станки работают": "Visos staklės veikia", "Открыть": "Atidaryti", "Обозначения": "Žymėjimas",
  "Состав текущей смены": "Dabartinės pamainos sudėtis", "Состав смены": "Pamainos sudėtis", "Учтены отмеченные в табеле сотрудники": "Skaičiuojami darbo laiko apskaitoje pažymėti darbuotojai", "Состав появится после отметки табеля": "Sudėtis bus parodyta užpildžius darbo laiko apskaitą", "Механиков": "Mechanikų",
  "Подготавливаем журналы": "Ruošiami žurnalai", "Все журналы синхронизированы. Программа готова к работе.": "Visi žurnalai sinchronizuoti. Programa paruošta darbui.", "Проверить снова": "Tikrinti dar kartą", "Повторить": "Bandyti dar kartą", "Проверить": "Tikrinti", "Рабочая смена идёт": "Darbo pamaina vyksta", "Завершить смену": "Baigti pamainą", "Смена не начата": "Pamaina nepradėta", "Перейти к табелю": "Eiti į darbo laiko apskaitą",
  "Быстрый контроль весов": "Greita svarstyklių patikra", "Введите показание и нажмите Enter — программа сразу перейдёт к следующим весам.": "Įveskite rodmenį ir spauskite Enter — programa pereis prie kitų svarstyklių.", "Одна запись": "Vienas įrašas", "Начать обход 13 весов": "Pradėti 13 svarstyklių patikrą", "Проверено сегодня": "Patikrinta šiandien", "В пределах допуска": "Leistinose ribose", "Вне допуска": "Už leistinų ribų", "Уникальных весов": "Unikalios svarstyklės", "Нужен комментарий": "Reikalingas komentaras", "Отклонений нет": "Nukrypimų nėra", "Период": "Laikotarpis", "Отправлено": "Išsiųsta", "В очереди": "Eilėje", "Дата": "Data", "Весы": "Svarstyklės", "Факт": "Faktas", "Отклонение": "Nukrypimas", "Результат": "Rezultatas", "Исполнитель": "Vykdytojas", "Состояние записи": "Įrašo būsena",
  "Рабочее время и смены": "Darbo laikas ir pamainos", "Табель участка": "Skyriaus darbo laiko apskaita", "Начало смены": "Pamainos pradžia", "Кто сегодня работает": "Kas šiandien dirba", "График смен": "Pamainų grafikas", "Цикл 2/2 и часы": "2/2 ciklas ir valandos", "Табель месяца": "Mėnesio apskaita", "Факт и отсутствие": "Faktas ir nebuvimas",
  "Расход упаковки": "Pakuočių sunaudojimas", "Вид упаковки": "Pakuotės tipas", "Нажмите на нужную позицию. Рядом показан уже взятый итог за день.": "Pasirinkite reikiamą poziciją. Šalia rodomas jau paimtas dienos kiekis.", "Уже взято сегодня": "Paimta šiandien", "Быстрый ввод": "Greitas įvedimas", "Выберите упаковку": "Pasirinkite pakuotę", "Сначала выберите позицию слева.": "Pirmiausia pasirinkite poziciją kairėje.", "Количество": "Kiekis", "Новое количество будет прибавлено к итогу за сегодня. Только целое положительное число.": "Naujas kiekis bus pridėtas prie šiandienos rezultato. Leidžiamas tik teigiamas sveikasis skaičius.", "Прибавить к итогу": "Pridėti prie rezultato",
  "Склад упаковки": "Pakuočių sandėlis", "Журнал несоответствий": "Neatitikčių žurnalas", "Журнал инцидентов": "Incidentų žurnalas", "Спецификация продуктов": "Produktų specifikacijos", "Склад запчастей": "Atsarginių dalių sandėlis", "Склад СИЗ": "AAP sandėlis", "Очистка циклонов": "Ciklonų valymas", "Документы": "Dokumentai", "Персонал": "Personalas", "График отпусков": "Atostogų grafikas", "Настройки": "Nustatymai",
  "Язык и оформление": "Kalba ir išvaizda", "Язык": "Kalba", "Тема": "Tema", "Тёмная": "Tamsi", "Светлая": "Šviesi", "Дата и время": "Data ir laikas", "Пароли учётных записей": "Paskyrų slaptažodžiai", "Учётная запись": "Paskyra", "Текущий пароль": "Dabartinis slaptažodis", "Новый пароль": "Naujas slaptažodis", "Повторите новый пароль": "Pakartokite naują slaptažodį", "Сменить пароль": "Keisti slaptažodį", "Сотрудники участка": "Skyriaus darbuotojai", "+ Добавить сотрудника": "+ Pridėti darbuotoją", "Должность": "Pareigos", "Статус": "Būsena", "Активен": "Aktyvus", "В архиве": "Archyve", "Изменить": "Keisti", "Вернуть": "Grąžinti", "В архив": "Į archyvą", "Сохранить": "Išsaugoti", "Отмена": "Atšaukti", "Продолжить": "Tęsti", "Закрыть": "Uždaryti",
  "Дни рождения": "Gimtadieniai", "Напоминания начальника": "Administracijos priminimai", "Сегодня день рождения": "Gimtadienis šiandien", "Через 3 дня": "Po 3 dienų", "Через неделю": "Po savaitės", "Конфликт": "Konfliktas", "Демо": "Demonstracija", "Аннулировано": "Anuliuota", "Синхронизация": "Sinchronizavimas", "Записей пока нет": "Įrašų dar nėra", "Нажмите «Новая запись», чтобы начать.": "Spustelėkite „Naujas įrašas“, kad pradėtumėte.", "Новая запись": "Naujas įrašas", "Исправление": "Taisymas", "Аннулирование": "Anuliavimas",
  "Коробки с логотипом GARANT (широкая) 430×285×255": "Dėžės su GARANT logotipu (plačios) 430×285×255", "Коробки с логотипом Garant (узкая) 570×210×249": "Dėžės su Garant logotipu (siauros) 570×210×249", "Бумага Dochems 37 GSM": "Dochems popierius 37 GSM", "Банка килла прозрачная": "Skaidrus Killa indelis", "Банка килла зелёная": "Žalias Killa indelis", "Крышка килла зелёная": "Žalias Killa dangtelis", "Банка ДЗ прозрачная": "Skaidrus DZ indelis", "Банка ДЗ зелёная": "Žalias DZ indelis", "Крышка ДЗ чёрная": "Juodas DZ dangtelis", "Крышка ДЗ белая": "Baltas DZ dangtelis"
};

const DICTIONARIES = Object.freeze({ en: RU_EN, lt: RU_LT });

function preserveWhitespace(value, translated) {
  const before = value.match(/^\s*/)?.[0] ?? "";
  const after = value.match(/\s*$/)?.[0] ?? "";
  return `${before}${translated}${after}`;
}

export function translateUiText(value, language) {
  if (language === "ru" || typeof value !== "string") return value;
  const dictionary = DICTIONARIES[language] ?? {};
  const key = value.trim();
  const translated = dictionary[key];
  if (translated) return preserveWhitespace(value, translated);
  const patterns = language === "en"
    ? [[/^Сегодня · /, "Today · "], [/^Версия /, "Version "], [/^В ремонте: /, "Under repair: "], [/^Требуют внимания: /, "Need attention: "]]
    : [[/^Сегодня · /, "Šiandien · "], [/^Версия /, "Versija "], [/^В ремонте: /, "Remontuojama: "], [/^Требуют внимания: /, "Reikia dėmesio: "]];
  for (const [expression, replacement] of patterns) {
    if (expression.test(key)) return preserveWhitespace(value, key.replace(expression, replacement));
  }
  return value;
}

export function localizeElement(element, language) {
  if (!element || language === "ru") return;
  const walker = document.createTreeWalker(element, NodeFilter.SHOW_TEXT);
  const nodes = [];
  while (walker.nextNode()) nodes.push(walker.currentNode);
  nodes.forEach(node => { node.nodeValue = translateUiText(node.nodeValue, language); });
  element.querySelectorAll("[placeholder],[title],[aria-label]").forEach(node => {
    ["placeholder", "title", "aria-label"].forEach(attribute => {
      if (node.hasAttribute(attribute)) node.setAttribute(attribute, translateUiText(node.getAttribute(attribute), language));
    });
  });
}
